config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :accomodations, only: [:index, :new, :show, :create] do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:index, :destroy] do
    member do
      patch :accept
      patch :decline
    end
  end

  root to: "pages#home"
end

app/models/accomodation.rb
class Accomodation < ApplicationRecord
  has_many_attached :photos
  belongs_to :user
  has_many :bookings
  has_many :accomodation_experiences, dependent: :destroy
  has_many :experiences, through: :accomodation_experiences

  validates :title, presence: true
  validates :price, presence: true, numericality: { only_float: true }
  validates :capacity, presence: true, numericality: { only_integer: true }
  validates :localisation, presence: true
  geocoded_by :localisation
  after_validation :geocode, if: :will_save_change_to_localisation?
end

app/models/accomodation_experience.rb
class AccomodationExperience < ApplicationRecord
  belongs_to :accomodation
  belongs_to :experience
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :accomodation
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true

  scope :ordered, -> { order(created_at: :desc) }
end

app/models/experience.rb
class Experience < ApplicationRecord
  has_many :bookings

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :accomodations, dependent: :destroy
  has_many :bookings
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/accomodations_controller.rb
class AccomodationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @accomodations = Accomodation.all
    @accomodation = Accomodation.new
    if params[:localisation].present? && params[:capacity].present?
      @accomodations = @accomodations.where("localisation ILIKE ?", "%#{params[:localisation]}%").and(@accomodations.where("capacity >= ?", params[:capacity]))
    elsif params[:capacity].present?
      @accomodations = (@accomodations.where("capacity >= ?", params[:capacity]))
    else
      @accomodations = Accomodation.all
    end
    if params[:category].present?
      @accomodations = @accomodations.where(category: params[:category])
    end
    @markers = @accomodations.geocoded.map do |a|
      {
        lat: a.latitude,
        lng: a.longitude,
        info_window_html: render_to_string(partial: "accomodations/info_window", locals: {a: a}, formats: :html)
      }
    end
    respond_to do |format|
      format.html
      format.json do
        render json: {
          list_partial: render_to_string(partial: 'accomodations/accomodation_list', locals: { accomodations: @accomodations, markers: @markers }, formats: :html)
        }
      end
    end
  end

  def new
    @accomodation = Accomodation.new
  end

  def show
    @accomodation = Accomodation.find(params[:id])
    @booking = Booking.new
    @experiences = @accomodation.experiences

    @markers = [

      {
        lat: @accomodation.latitude,
        lng: @accomodation.longitude
      }
    ]
  end

  def activity

  end

  def create
    @accomodation = Accomodation.new(accomodation_params)
    @accomodation.user = current_user
    @experience = Experience.first
    if @accomodation.save
      redirect_to accomodation_path(@accomodation)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def accomodation_params
    params.require(:accomodation).permit(:title, :description, :price, :localisation, :environment_tag, :capacity, :category, photos: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_accomodation, only: :create
  before_action :set_booking, only: [:accept, :decline, :destroy]

  def index
    @incoming_bookings = Booking.joins(:accomodation).where(accomodations: { user_id: current_user.id }).where('bookings.start_date >= ?', Date.today).order(:start_date)
    @outgoing_bookings = current_user.bookings.where('start_date >= ?', Date.today).order(:start_date)
  end

  def create
    @booking = Booking.new(bookings_params)
    @booking.user = current_user
    @booking.accomodation = @accomodation

    if @booking.save
      redirect_to bookings_path
    else
      render "accomodations/show", status: :unprocessable_entity
    end
  end

  def accept
    if @booking.update(status: 'accepted')
      redirect_to bookings_path, notice: 'Booking was successfully accepted.'
    else
      redirect_to bookings_path, alert: 'Failed to accept the booking.'
    end
  end

  def decline
    if @booking.update(status: 'declined')
      redirect_to bookings_path, notice: 'Booking was successfully declined.'
    else
      redirect_to bookings_path, alert: 'Failed to decline the booking.'
    end
  end

  def destroy
    if @booking.destroy
      redirect_to bookings_path, notice: 'Booking was successfully deleted.'
    else
      redirect_to bookings_path, alert: 'Failed to delete the booking.'
    end
  end

  private

  def bookings_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_accomodation
    @accomodation = Accomodation.find(params[:accomodation_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @accomodations = Accomodation
    .left_joins(:bookings)
    .group('accomodations.id')
    .order('COUNT(bookings.id) DESC')
    .select('accomodations.*, COUNT(bookings.id) as bookings_count')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accomodations/_accomodation_list.html.erb
<div class="container d-flex flex-row" data-category-filter-target="list">
  <div class="container col-7 mx-2">
    <div class= "wrapper">
      <% accomodations.each do |a| %>
        <div class="card h-100" style="width: 100%">
          <%= link_to accomodation_path(a) do %>
           <% if a.photos.attached? %>
            <%= cl_image_tag a.photos.first.key, class: "card-img-top img-custo", alt: a.title %>
           <% else %>
          <img class="card-img-top img-custo" src="<%= a.images %>" alt="<%= a.title %>">
           <% end %>
          <% end %>
          <div class="card-body">
            <div class="d-flex flex-row justify-content-between mb-1">
              <p class="tag"><%= a.category %></p>
              <p><strong><%= a.price %>€</strong>/night</p>
            </div>
            <h5 class="card-title"><%= link_to a.title, accomodation_path(a) %></h5>
            <p class="card-text"><%= a.description %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="container col-5 mx-2">
    <div class="top-sticky" style="width: 100%; height: 460px;"
        data-controller="map"
        data-map-markers-value="<%= markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/accomodations/_info_window.html.erb
<%= link_to "/accomodations/#{a.id}" do %>
  <img class = "img-window" src="<%= a.images %>" alt="<%= a.title %>">
<% end %>
<p><%= link_to a.title, "/accomodations/#{a.id}" %></p>
<p><b><%= a.price %>€</b></p>

app/views/accomodations/index.html.erb
<%= form_with url: accomodations_path, method: :get, html: { data: { controller: "category-filter" }} do %>
  <div class="border-bottom d-flex flex-row justify-content-around py-3">
    <div class= "col-5 search-bar">
        <%= label_tag :destination, "Destination", class: "search-label" %>
        <%= text_field_tag :localisation, params[:localisation], class: "search-input", placeholder: "Paris, France" %>
        <%= label_tag :capacity, "Guests", class: "search-label" %>
        <%= select_tag(:capacity, options_for_select((1..10).to_a, params[:capacity].to_i), class: "search-input") %>
        <%= submit_tag "Search", class: "search-button" %>
    </div>
  </div>
  <div class = "container mx-5 my-3">
    <div class = "mx-5 col-6 d-flex flex-row justify-content-around">
      <div class ="text-center">
        <%= radio_button_tag :category, "cabin", data: { action:"change->category-filter#submit" } %>
        <i class="fa-solid fa-campground mx-1"></i><%= label_tag :cabin_category, "Cabin", style:"font-size: 14px;" %>
      </div>
      <div class ="text-center">
        <%= radio_button_tag :yurt_category, "yurt", data: { action:"change->category-filter#submit" } %>
        <i class ="fa-solid fa-tent mx-1"></i><%= label_tag :yurt_category, "Yurt", style:"font-size: 14px;" %>
      </div>
      <div class = "text-center">
        <%= radio_button_tag :category, "container", data: { action:"change->category-filter#submit" } %>
        <i class = "fa-solid fa-box mx-1" ></i><%= label_tag :container_category, "Container", style:"font-size: 14px;" %>
      </div>
      <div class = "text-center">
        <%= radio_button_tag :category, "tiny house", data: { action:"change->category-filter#submit" } %>
        <i class = "fa-solid fa-house mx-1" ></i><%= label_tag :tiny_category, "Tiny house", style:"font-size: 14px;" %>
      </div>
    </div>
  </div>
  <%= render partial: 'accomodations/accomodation_list', locals: { accomodations: @accomodations, markers: @markers } %>
<% end %>

app/views/accomodations/new.html.erb
<div class="banner-title">
<div class="container p-5">
<h1 class="banner-title">Create a new accomodation</h1>
</div>
</div>
<div class="container">


<%= simple_form_for @accomodation do |f| %>
    <div class="d-flex">
        <div class="container p-5 m-2">
          <h4 class="question-title">Question 1</h4>
          <h3>Give your accomodation a title *</h3>
          <%= f.input :title, label: false%>
        </div>

        <div class="container p-5 m-2">
          <h4 class="question-title">Question 2</h4>
          <h3>Add a description</h3>
          <%= f.input :description, as: :text, label: false %>
        </div>
    </div>

    <div class="container p-5 m-2">
      <h4 class="question-title">Question 3</h4>
      <h3>Which of the following best describes your accommodation?</h3>
        <div class="type d-flex">
      <% [['Yurt', 'yurt', 'fa-tent'], ['Cabin', 'cabin', 'fa-campground'], ['Tiny House', 'tiny house', 'fa-house-house'], ['Container', 'container', 'fa-shipping-box']].each do |label, value, icon_class| %>
      <div class="radio-item">
        <%= f.radio_button :category, value, id: "category_#{value}", class: "hidden-radio" %>
        <label for="category_<%= value %>">
          <i class="fas <%= icon_class %>"></i>
          <%= label %>
        </label>
      </div>
    <% end %>
  </div>
    </div>

    <div class="container p-5 m-2">
      <h4 class="question-title">Question 4</h4>
      <h3>Where is your accomodation? *</h3>
      <%= f.input :localisation, label: false,
      input_html: {data: {address_autocomplete_target: "localisation"}, class: "d-none"},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
    </div>

  <div class="d-flex">
      <div class="container p-5 m-2">
        <h4 class="question-title">Question 5</h4>
        <h3>What's the price for one night? *</h3>
        <%= f.input :price, wrapper_html: { class: "mb-0-important" }, input_html: { value: 0, 'data-price-incrementation-target': 'price', class:"increment"}, label: false  %>
        </div>

      <div class="container p-5 m-2">
        <h4 class="question-title">Question 6</h4>
        <h3>What's the capacity ? *</h3>
          <div class="d-flex container-incrementation justify-content-center align-items-center" data-controller="capacity-incrementation">
         <button type="button" class="incrementation_button" data-action="click->capacity-incrementation#decrement">-</button>
          <%= f.input :capacity, wrapper_html: { class: "mb-0-important" }, input_html: { value: 1, 'data-capacity-incrementation-target': 'capacity', readonly: true, class:"increment"}, label: false  %>
        <button type="button" class="incrementation_button" data-action="click->capacity-incrementation#increment">+</button>
      </div>
  </div>
      </div>


<div class="container p-5 m-2">
      <h4 class="question-title">Question 7</h4>
      <h3>Which is the type of environment for your accomodation?</h3>
       <div class=" container type d-flex">
      <% [['Mountain', '0'], ['Coast', '1'], ['Countryside', '2'], ['Urban', '3']].each do |label, value| %>
      <div class="radio-item">
        <%= f.radio_button :environment_tag, value, id: "environment_tag#{value}", class: "hidden-radio" %>
        <label for="environment_tag<%= value %>">
          <%= label %>
        </label>
      </div>
    <% end %>
  </div>
</div>

    <div class="container p-5 m-2">
    <h4 class="question-title">Add images</h4>
    <h3>Click or drag and drop to add images</h3>

      <div class="drag-drop" data-controller="dropzone" data-action="click->dropzone#chooseFile">
        <%= f.input :photos, as: :file, input_html: { multiple: true, data: { dropzone_target: "fileInput" } }, label: false %>
        <div data-dropzone-target="preview"></div>

      </div>
    </div>


    <div class="container p-5 m-2">
      <%= f.submit "Create my new accomodation", class: "btn btn-success w-100" %>
    </div>
<% end %>
</div>

app/views/accomodations/show.html.erb
<div class="page_wrap" data-controller="price-detail" data-price-detail-price-value="<%= @accomodation.price.round %>" data-price-detail-capacity-value="<%= @accomodation.capacity %>" data-price-detail-activity-price-value="<%= @accomodation.experiences&.first&.price&.round %>" >

  <div class="show_hero_wrap">
  <div class="container-show" style="padding-bottom: 2.5rem">
    <div class="show_hero_layout">
      <div class="show_hero_left">
        <div class="show_header">
        <h1 class="h1"><%= @accomodation.title %></h1>
        <div class="header_info">
          <div class="header_tag_wrap">
            <div class="icon_wrapper">
            <i class="fa-solid fa-user"></i>
            <p><%= @accomodation.capacity %> people</p>
            </div>
            <div class="icon_wrapper">
            <i class="fa-solid fa-tree"></i>
            <p><%= @accomodation.environment_tag %> </p>
            </div>
          </div>
          <div class="icon_wrapper">
          <i class="fa-solid fa-location-dot"></i>
          <p><%= @accomodation.localisation %></p>
        </div>
        </div>
        </div>
        <div class="show_img_wrap">
        <% if @accomodation.photos.attached? %>
          <%= cl_image_tag @accomodation.photos.first.key, class: "absolute_img", alt: "Image of an accomodation" %>
          <% else %>
          <img class="absolute_img" src="<%= @accomodation.images %>" alt="<%= @accomodation.title %>">
        <% end %>
      </div>
      <div class="show_description_wrap">
        <h2 class="h6">Description</h2>
        <p><%= @accomodation.description %></p>
      </div>
      </div>
      <div class="show_hero_right">
        <h2 class="h5">Select a date</h2>
        <%= simple_form_for [@accomodation, @booking] do |f| %>
        <div class="form_wrap">
          <div class="dates_wrap">
            <div class="date_wrap">
              <%= f.input :start_date, as: :string, input_html: { data: { controller: "datepicker", price_detail_target: "startDate" } } %>
            </div>
            <div class="date_wrap">
              <%= f.input :end_date, as: :string, input_html: { data: { controller: "datepicker", price_detail_target: "endDate", action: "change->price-detail#toggle" } } %>
            </div>
          </div>
          <div class="divider"></div>
          <div class="activity_wrap">
            <h6 class="h6">Your experiences</h6>

            <div class="activity_card d-none" data-price-detail-target="activityWrap">
              <% @experiences.each do |e| %>
                <div class="activity_card_frame">
                  <div class="activity_card_height">
                    <img
                      class="absolute_img"
                      src="<%= e.image_url %>"
                      alt=""
                    />
                  </div>
                </div>
                <div class="form_activity_wrap">
                  <p class="text-color-black"> <%= e.title %> </p>
                  <p> <span class="text-weight-medium"><%= e.price.round %></span>€/guest </p>
                </div>
              <% end %>
            </div>




          </div>
          <div class="divider"></div>
          <div class="prices_wrap">
            <h6 class="h6">Pricing details</h6>



            <div class="prices_wrap d-none" data-price-detail-target="priceNightWrapper">
              <div class="price_line_wrap">
                <div class="price_line_left">
                  <p class="text-weight-medium">Price per night</p>
                  <div class="logic_price_wrap">
                    <p><%= @accomodation.price.round %>€</p>
                    <p>x</p>
                    <p data-price-detail-target="numberOfNights"></p>
                  </div>
                </div>
                <p data-price-detail-target="total"></p>
              </div>
            </div>


            <div class="prices_wrap d-none" data-price-detail-target="priceActivityWrapper">
              <div class="price_line_wrap">
                <div class="price_line_left">
                  <p class="text-weight-medium">Price per activity</p>
                  <div class="logic_price_wrap">
                    <p><%= @accomodation.experiences&.first&.price&.round %>€</p>
                    <p>x</p>
                    <p> <%= @accomodation.capacity %> </p>
                  </div>
                </div>
                <p data-price-detail-target="totalActivity"></p>
              </div>
            </div>



          </div>
        </div>
        <%= f.button :submit, class: "button", style: "margin-top: 2rem" %>
        <% end %>
      </div>
    </div>
  </div>
  </div>

  <div class="map_wrap">
  <div class="container-show">
    <div class="map_layout">
      <h2 class="h2 mb-3">Localisation</h2>
      <div class="map_contain" style="width: 100%; height: 460px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
  </div>

  <% if @experiences.any? %>
    <div class="show_activity_wrap">
      <div class="container-show">
        <h2 class="h2 mb-5">Activity near this accomodation</h2>
        <div class="show_activity_layout">
            <% @experiences.each do |e| %>
              <div class="activity_card_item">
                <div class="activity_card_img_frame">
                  <div class="activity_card_img_height">
                    <img class="absolute_img" src="<%= e.image_url %>">
                    <div class="activity_img_tag"><%= e.kind %></div>
                  </div>
                </div>
                <div class= "activity_card_info_wrap">
                  <h3 class="h6"><%= e.title %></h3>
                  <p class= "text-style-two-lines"> <%= e.description %></p>
                  <p class="activity_card_price"> <%= e.price.round %>€/personne</p>
                </div>
                <button class="button" data-action="click->price-detail#toggleActivity" data-price-detail-price-param= <%= e.price.round %>>Add activity to booking</button>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/index.html.erb
<%# Add missing import statement for link_to helper method
<%# Add the following line at the top of the selected code block
<%# require 'action_view/helpers/url_helper' %>
<div class="containerr">
  <div class="dashboard">
    <h2>Mon dashboard</h2>
    <div class="sections">
      <div class="section">
        <h5>Réservations à venir</h5>
        <div class="cardds">
          <% @incoming_bookings.each do |booking| %>
            <% accomodation = booking.accomodation %>
            <div class="cardd">
              <div class="cardd-header">
                <span class="status-buttons">
                  <%= button_to 'Accepter', accept_booking_path(booking), method: :patch, class: 'accept-link' %>
                  <%= button_to 'Refuser', decline_booking_path(booking), method: :patch, class: 'decline-link' %>
                </span>
                <span class="icon"><i class="fa-solid fa-calendar-plus"></i></span>
              </div>
              <div class="cardd-body">
                <% if accomodation.images.present? %>
                  <img src="<%= accomodation.images %>" alt="<%= accomodation.title %>" class="accommodation-image" />
                <% end %>
                <p class="name mt-1"><%= accomodation.user.first_name %></p>
                <p class="dates mt-4"><%= booking.start_date.strftime('%-d %b.') %> - <%= booking.end_date.strftime('%-d %b.') %></p>
                <p class="location mt-4"><%= accomodation.localisation %></p>
                <div class="cardd-footer">
                  <p class="status mt-4"><%= booking.status %></p>
                  <% if booking.status == 'declined' %>
                    <%= button_to 'Supprimer', booking_path(booking), method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer cette réservation ?' }, class: 'delete-link btn btn-danger' %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <div class="section">
        <h5 class= "mt-5">Voyages à venir</h5>
        <div class="cardds">
          <% @outgoing_bookings.each do |booking| %>
            <% accomodation = booking.accomodation %>
            <div class="cardd">
              <div class="carddd-header mb-1">
                <%
                  days_remaining = (booking.start_date.to_date - Date.today).to_i
                  status_message = if days_remaining > 30
                                    "Dans #{(days_remaining / 30.0).round} mois"
                                  elsif days_remaining > 0
                                    "Dans #{days_remaining} jours"
                                  elsif days_remaining == 0
                                    "Aujourd'hui"
                                  else
                                    "Date passée"
                                  end
                %>
                <span class="status"><%= status_message %></span>
                <span class="icon"><i class="fa-solid fa-suitcase"></i></span>
              </div>
              <div class="cardd-body">
                <% if accomodation.images.present? %>
                  <img src="<%= accomodation.images %>" alt="<%= accomodation.title %>" class="accommodation-image" />
                <% end %>
                <p class="name mt-1"><%= booking.user.first_name %></p>
                <p class="dates mt-4"><%= booking.start_date.strftime('%-d %b.') %> - <%= booking.end_date.strftime('%-d %b.') %></p>
                <p class="location mt-4"><%= accomodation.localisation %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GreenEscape</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v3.4.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/accomodations", class: "navbar-brand" do %>
      <p>Green escape</p>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="navbar-nav me-auto">
        <div>
        <% if user_signed_in? %>
          <%= link_to new_accomodation_path do %>
          <button class="btn nav-item-button">+ Add accomodation</button>
        <% end %>
        </div>
        <div class="nav-item dropdown item-center">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa-solid fa-user avatar avatar-size"></i>
            <%# <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
              <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
        </div>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </div>
    </div>
  </div>
</div>
    <%= yield %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home_hero_wrap">
  <div class="container">
    <div class="home_hero_layout">
      <h1 class="h1 text-align-center mb-6">Escape from the city<br>Green Escape</h1>
      <div class="accomodation_wrap">
        <% @accomodations.each do |a| %>
          <div class="card" style="width: 100%">
            <%= link_to accomodation_path(a) do %>
              <img class="card-img-top img-custo" src="<%= a.images %>" alt="<%= a.title %>">
            <% end %>
            <div class="card-body">
              <div class="d-flex flex-row justify-content-between mb-1">
                <p class="tag"><%= a.category %></p>
                <p><strong><%= a.price %>€</strong>/night</p>
              </div>
              <h5 class="card-title"><%= link_to a.title, accomodation_path(a) %></h5>
              <p class="card-text"><%= a.description %></p>
              <p>Bookings: <%= a.bookings_count %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <% if session[:alert_kind] == 'decline' %>
    <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
  <% else %>
    <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
  <% end %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>